USE [Telecom]
GO

/****** Object:  Table [dbo].[Dim_IMSI_Reference]    Script Date: 3/10/2025 12:47:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Dim_IMSI_Reference](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IMSI] [varchar](9) NULL,
	[Subscriber_ID] [int] NULL,
 CONSTRAINT [PK_Dim_IMSI_Reference] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

